name: Unit Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clear Maven cache
        run: mvn clean install -U

      - name: Run tests
        run: mvn clean test

      - name: Show Maven effective POM
        run: mvn help:effective-pom
